title: Fast Machine Learning Foundation
short_title: FastML Foundation
email: fml@fastmachinelearning.org

one_liner: A non-profit foundation advancing real-time and accelerated ML for fundamental sciences
description: >
  Fast Machine Learning Foundation is a non-profit created to develop tools and training for machine learning
  algorithms in unique and challenging scientific applications. We bring together physicists, engineers, and
  computer scientists to build and deploy real-time, on-detector, low-latency systems and high-throughput
  heterogeneous computing workflows that enable discovery from the world's biggest colliders to the cosmos.
news_byline: >
  We share upcoming and recent events for the community.

collaboration:
  byline: We are a community that fosters knowledge transfer of accelerated and real-time artificial intelligence for fundamental science. By participating, you agree to abide by our code of conduct and collaboration policies.

navbar:
  logo: /images/fml.png
  links:
    - name: About
      link: "#about" # Note that for links to autoscroll to anchors on the main page, only the #anchor is needed (no preceding slash)
      autoscroll: true
    - name: Events
      link: "#events"
      autoscroll: true
    - name: Resources
      link: "#resources"
      autoscroll: true
    - name: Collaboration
      link: "#collaboration"
      autoscroll: true
    - name: Sponsors/Partners
      link: "#sponsors"
      autoscroll: true
    - name: Governance
      link: "/governance.html"
      autoscroll: false
    - name: Contact
      link: "mailto:fml@fastmachinelearning.org"
      autoscroll: false

footer:
  links:
    - name: HLS4ML Homepage
      link: https://fastmachinelearning.org/hls4ml/
    - name: SuperSONIC Homepage
      link: https://fastmachinelearning.org/SuperSONIC/
    - name: GitHub Repositories
      link: https://github.com/fastmachinelearning

exclude: ["CNAME", "license.txt", "README.md"]
